### ISSUE TITLE
Error phphtmlparser\dom 

### ISSUE THREAD

**Issue by JohnMica** [OleVik/grav-plugin-imgsrcset#1]
Hi there. 
It seems that once enabling these plugins there is an error causing the website to stop working. I opened an issue on grav thinking is the system but as soon as I disabled your plugins (both image plugins) the site is back to normal. 
Error is https://github.com/getgrav/grav/issues/849
Hope this helps with further development

**Comment by OleVik** [comment]
It will, thank you for raising the issue. This can be traced to this plugin, that is ImgSrcset, as ImgCaptions does not use a DOMParser. Would you mind sharing your `imgsrcset.yaml`-file, or are you using the plugins defaults? Also, were you able to locate the error in PHP's `error_log`?

**Comment by JohnMica** [comment]
Hi it's the default settings with only the plugin activated. Link is here https://www.dropbox.com/sh/ikoab3neb3n8yr7/AABghDaSecY0-3J7pw5veiN1a?dl=0

**Comment by OleVik** [comment]
The settings and plugin-files are all correct. Could you share a copy of your `user`-directory and potentially PHP's error_log? The plugin has been tested on both version 5.6 and 7 of PHP, so the version should not be an issue.

**Comment by JohnMica** [comment]
Here goes the link for the whole site 
https://www.dropbox.com/sh/0udjvi217if75w8/AAB4wznbMLJcepADkoO987dWa?dl=0

Hope this helps. Not sure where the Php log file is. System is using Php 7 live and both 5.6.x &7 local. Error appears on both versions.

**Comment by OleVik** [comment]
I did some debugging using your files as base, could you try setting `twig_first` in `system.yaml` to `true`? It is located in the pages-options, like this:

```
pages:
  twig_first: true
```

In your options it was set to `false`, and it appears that this might be a requirement of the plugin.

**Comment by JohnMica** [comment]
changed the twig - no more errors from the parse, however the front page is no longer loading the photos, css or markdown properly as per the photo attached.
cache cleared 

twig first - activated
![captura de ecran din 2016 05 29 la 17 56 09](https://cloud.githubusercontent.com/assets/7076631/15634896/3e62925c-25c7-11e6-8cc2-05cb259de68b.png)

twig first - false
![captura de ecran din 2016 05 29 la 18 03 06](https://cloud.githubusercontent.com/assets/7076631/15634917/b2d6367a-25c7-11e6-99ba-6d4293b5f1b5.png)

so leaving twig first is not an option yet for me. I am using the modular.twig with slider, text and hopefully in the near future the contact/subscribe respective modulars.

**Comment by OleVik** [comment]
This is unrelated to `twig_first` and the plugin itself. As per the errors, they are letting you know that the images cannot be found, which is because they do not exist where they are expected. How have you specified the image?

The plugin only does the following:
1. Accesses processed Markdown.
2. Finds `img`-elements.
3. Uses the `src`-attribute to generate a `srcset`-attribute based on the `widths` specified.
4. Sets the `sizes`-attribute based on the `sizes` specified.
5. Returns the changed content for further processing by Grav.

So, for example with an image named `street.jpg` the content of a page's folder would look like this (with default `widths`):

```
page.md
street.jpg
street-320.jpg
street-480.jpg
street-640.jpg
street-960.jpg
street-1280.jpg
street-1600.jpg
street-1920.jpg
street-2240.jpg
```

**Comment by JohnMica** [comment]
![captura de ecran din 2016 05 29 la 19 42 10](https://cloud.githubusercontent.com/assets/7076631/15635401/7d45c364-25d5-11e6-8d18-56d3c57183b0.png)

images are placed in each section's folder but when twig_first and imgsrcset are active the errors regarding the images appear. when twig_first - false then images are found and rendered. As you can see the images are actually in their specified folder/route but only in the original size. 

should i delete all images and then add them again ? would this have anything to do with the errors ?
![captura de ecran din 2016 05 29 la 19 49 14](https://cloud.githubusercontent.com/assets/7076631/15635469/c6cc97c8-25d6-11e6-82a7-0baf209858b5.png)

**Comment by OleVik** [comment]
The source image appears to be there, but not the sizes that the browser requests. The difference here is that the 404 error revealed by the Developer Console tells us that it is not the plugin or Grav itself, but rather that the images sought after actually do not exist. Thus `twig_first` is a required condition of the plugin, as Twig must be rendered before other effects are applied upon the Markdown-source.

From your example image, of the folder and file hierarchy, I do not see a file named `Canabis1-320.jpg`, `Canabis1-480.jpg`, etc. Note, that the plugin does not generate these images for your. It is simply an alternative way of using such images, generated by other means than Grav.

Your second example, of the Developer Console output, shows that the plugin is having the desired effect: It generates and applies the `srcset`\- and `sizes`-attributes. For an example of how to generate these images, see [this gist](https://gist.github.com/OleVik/f2c8b51a7153743b13607072c27cf8d2#file-gulpfile-js).

**Comment by JohnMica** [comment]
I must have understood that it will automatically create such images names 320, 940 , etc...

This will explain the error not finding the images. 
However the markdown is not interpreted when twig_first true ... Could be a grav bug then?

**Comment by OleVik** [comment]
That should not be the case. From [the documentation](https://learn.getgrav.org/content/headers):

**Process Twig First**

```
twig_first: false
```

> If set to `true` Twig processing will occur before any Markdown processing. This can be particularly useful if your twig generates markdown that needs to be available in order to be processed by the Markdown compiler. One thing to note, if have `cache_enable: false` **and** `twig_first: true` page caching is effectively disabled.

Effectively, it tells Grav that Twig should be processed before Markdown. My guess is that this also processes things like `special_chars`, which would not allow manipulation of the DOM on the processed Markdown because the code is no longer valid.

**Comment by JohnMica** [comment]
Thanks Ole for all the info. One more thing, rendering of the page changes when twig first. But I have taken another look and also the page CSS seems a bit broken where the button is no longer placed under the whole text positioned centre. If you check the live site canabismedical.ro you will see the difference in layout (live site has twig first false) where the local development (images sent so far) has twig first true/.

**Comment by JohnMica** [comment]
Good luck with further development and hopefully in the near future the little issue will disappear :)
