### ISSUE TITLE
Add support for Gantry5 into Grav admin

### ISSUE THREAD

**Issue by Getron** [OleVik/grav-plugin-imgsrcset#5]
I just try to install this plugin, and the "Appearence" of Gantry5, Theme Helium is not showed properly on Grav admin.

Please, check this plugin with Gantry5, and you will see the problem in Grav admin, under "Appearence" left Menu, if the Default Theme is "g5_helium"

**Comment by flaviocopes** [comment]
@OleVik just add a `if (!$this->isAdmin()) {}` in the onPageContentProcessed event, that should be enough.

**Comment by OleVik** [comment]
Released [v1.0.1](https://github.com/OleVik/grav-plugin-imgsrcset/releases/tag/v1.0.1), which restricts operation to front-end only. Thanks @flaviocopes for quick solution and @Getron for reporting the issue.
