### ISSUE TITLE
Disabling on specific pages

### ISSUE THREAD

**Issue by MelleNi** [OleVik/grav-plugin-imgsrcset#7]
Hey,

I know this hasn't been updated in quite sometime, but I like what it does. I've recently built a site where some pages need to use srcset for all images, and others don't. Is there a way to circumvene this plugin on specific pages?

Thank you!

**Comment by OleVik** [comment]
That should be possible, I'll run some tests when I'm home.

**Comment by OleVik** [comment]
This can be done in [v1.1.0](https://github.com/OleVik/grav-plugin-imgsrcset/releases/tag/v1.1.0), where you can adapt the settings [per Page](https://github.com/OleVik/grav-plugin-imgsrcset/#per-page-options):

```yaml
imgsrcset:
  enabled: true
  widths: widths
  sizes: sizes
```
