### ISSUE TITLE
Problem in HtmlNode breaks all pages

### ISSUE THREAD

**Issue by MelleNi** [OleVik/grav-plugin-imgsrcset#9]
Hey there,

Apparently the last update hadn't been properly downloaded on my site. I figured out just now and finally updated the plug-in. Sadly it now breaks my entire site. Turning it off 'removes the issue'.

The error I get on every page is:
`"Return value of PHPHtmlParser\Dom\HtmlNode::clear() must be an instance of PHPHtmlParser\Dom\void, none returned"`

It highlights a closing French bracket `}` on line `196` of `/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/HtmlNode.php`

Is this an easy fix?

**Comment by MelleNi** [comment]
Apparently I had to select a newer php version for this update.

**Comment by skinofthesoul** [comment]
Hey, I'm getting the same error. My PHP version is 7.0, could you tell me which one I should upgrade to? 
Thank you!

**Comment by MelleNi** [comment]
Hey, if I recall correctly the problem doesn’t occur with any other php version. So 7.1-.3 should be fine. But, another error may appear.
